version: '3'
networks:
  scheduler-network:
    driver: bridge
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - scheduler-network
  postgredb:
    image: postgres:alpine
    container_name: postgres-scheduler-app
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - scheduler-network
  schedulerapp:
    image: linbr/scheduler-app
    build: ./service/
    container_name: scheduler-app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      JAVA_OPTS: -Xmx2048m
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATABASE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgredb:5432/postgres
      SPRING_JPA_DATABASE: POSTGRESQL
      SPRING_JPA_HIBERNATE_DDLAUTO: update
      SPRING_JPA_PROPERTIES_JDBC_TIMEZONE: "GMT-03:00"
      SPRING_RABBITMQ_ADDRESSES: amqp://guest:guest@rabbitmq:5672/
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - postgredb
      - rabbitmq
    networks:
      - scheduler-network
  api:
    image: linbr/scheduler-api
    build: ./api/
    container_name: scheduler-api
    restart: always
    environment:
      JAVA_OPTS: -Xmx2048m
      SPRING_RABBITMQ_ADDRESSES: amqp://guest:guest@rabbitmq:5672/
    links:
      - rabbitmq:rabbitmq
    ports:
      - 8080:8080
    depends_on:
      - postgredb
      - rabbitmq
    networks:
      - scheduler-network