spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: "GMT-03"
logging:
  level:
    root: DEBUG
    web: DEBUG
    sql: DEBUG
debug: true